# Generated by Django 4.1 on 2022-11-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='startingPrice',
            field=models.IntegerField(default=0),
        ),
    ]
